import { About } from "@/components/About";
import { WorkExperience } from "@/components/WorkExperience";
import { Links } from "@/components/Links";
import { Skills } from "@/components/Skills";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<section>
					<About />
					<WorkExperience />
					<Skills />
					<Links />
				</section>
			</main>
		</>
	);
}
