import { Aside } from "@/components/Aside/Aside";
import { Header } from "@/components/Header";
import { About } from "@/components/Sections/About";
import { Links } from "@/components/Sections/Links";
import { Skills } from "@/components/Sections/Skills";
import { WorkExperience } from "@/components/Sections/WorkExperience";
import { user } from "@/data/user";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			{/* <Aside /> */}

			<main>
				<section>
					<ul>
						<li className="md:grid md:place-items-center">
							<About />
						</li>
						<li className="md:grid md:place-items-center">
							{user.workExperience && <WorkExperience />}
						</li>
						<li className="md:grid md:place-items-center">
							<Skills />
						</li>
						<li className="md:grid md:place-items-center">
							<Links />
						</li>
					</ul>
				</section>
			</main>
		</>
	);
}
